export { default as Dashbord } from "../Pages/User/Dashbord/Dashbord";
export { default as Hader } from "../components/Header/Hader";
export { default as Footer } from "../components/Footer/Footer";
export { default as TaskIndex } from '../Pages/User/Task/Index'
export { default as TaskList } from "../Pages/User/Task/TaskList";
export { default as TaskCreate } from "../Pages/User/Task/TaskCreate";
export { default as TaskUpdate } from "../Pages/User/Task/TaskUpdate";
export { default as MemberIndex } from "../Pages/User/Member/Index";
export { default as MemberList } from "../Pages/User/Member/MemberList";
export { default as PriveRoutstHandaler } from "../constant/PriveRoutstHandaler";
export { default as MemberCreate } from "../Pages/User/Member/MemberCreate";
export { default as MemberUpdate } from "../Pages/User/Member/MemberUpdate";